/**:
  ros__parameters:
    wheel_radius: 0.1
    wheel_width: 0.045
    wheel_base: 0.45 # between front wheel center and rear wheel center
    wheel_tread: 0.38 # between left wheel center and right wheel center
    front_overhang: 0.12 # between front wheel center and vehicle front
    rear_overhang: 0.16 # between rear wheel center and vehicle rear
    left_overhang: 0.075 # between left wheel center and vehicle left
    right_overhang: 0.075 # between right wheel center and vehicle right
    vehicle_height: 1.095 # vehicle height + sensor_kit height
    max_steer_angle: 3.14 # [rad]